speed up airflow partial deploy

diff --git a/.github/workflows/airflow-partial-deploy.yaml b/.github/workflows/airflow-partial-deploy.yaml
--- a/.github/workflows/airflow-partial-deploy.yaml
+++ b/.github/workflows/airflow-partial-deploy.yaml
@@ -54,6 +54,88 @@ env:
 
 jobs:
 
+  airflow_instances_check:
+
+    runs-on: ${{ inputs.RUNS_ON }}
+
+    permissions: # github oidc
+      id-token: write
+      contents: read
+
+    steps:
+
+      - name: echo
+        run: |
+          echo AWS_REGION ${{ inputs.AWS_REGION }}
+          echo CDK_PREFIX ${{ inputs.CDK_PREFIX }}
+          echo ENVIRONMENT_LONG_NAME ${{ inputs.ENVIRONMENT_LONG_NAME }}
+          echo RUNS_ON ${{ inputs.RUNS_ON }}
+          echo SLACK_CHANNEL_ID ${{ inputs.SLACK_CHANNEL_ID }}
+          echo TARGET_AWS_ACCOUNT_ROLE_ARN ${{ inputs.TARGET_AWS_ACCOUNT_ROLE_ARN }}
+          echo "GITHUB_RUN_URL_FOR_SLACK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
+          echo "CHANGED_COUNT=0" >> $GITHUB_ENV
+          echo "DELETED_COUNT=0" >> $GITHUB_ENV
+
+      - name: Deployer Role with Github OIDC Provider
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+            role-to-assume: ${{inputs.TARGET_AWS_ACCOUNT_ROLE_ARN}}
+            aws-region: ${{inputs.AWS_REGION}}
+  
+      - name: List Redshift clusters
+        run: |
+          aws redshift describe-clusters --query 'Clusters[*].[ClusterIdentifier,ClusterStatus]' --output text --region ${{ inputs.AWS_REGION }}
+
+      - name: Resume Redshift ${{ inputs.CDK_PREFIX }} cluster
+        run: |
+          CLUSTER_ID=$(aws redshift describe-clusters --tag-keys Instance --tag-values ${{ inputs.CDK_PREFIX }} --tag-keys Stack --tag-values ${{ inputs.CDK_PREFIX }}-datainfra-v2-redshift --query 'Clusters[*].ClusterIdentifier' --output text --region ${{ inputs.AWS_REGION }})
+          echo "Redshift cluster id" $CLUSTER_ID
+
+          STATUS=`aws redshift describe-clusters --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}`
+          if [[ $STATUS == "available" ]]
+          then
+            echo "Cluster" $CLUSTER_ID "is already available, no action."
+          elif [[ $STATUS == "pausing" ]]
+          then
+            echo "Cluster" $CLUSTER_ID "is pausing, failing!"
+            exit 1
+          elif [[ $STATUS == "resuming" ]]
+          then
+            echo "Cluster" $CLUSTER_ID "is resuming, no action!"
+          else
+            echo "Resuming Redshift Cluster" $CLUSTER_ID "status" $STATUS
+            aws redshift resume-cluster --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}
+          fi
+        
+          # do we add a wait for it to resume here or just fire and forget?
+
+          STATUS=`aws redshift describe-clusters --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}`
+          echo "STATUS:" $STATUS
+
+      - name: List EC2 ${{ inputs.CDK_PREFIX }} Instances
+        run: |
+          INSTANCE_IDS=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters "Name=tag-key,Values=Instance" "Name=tag-value,Values=${{ inputs.CDK_PREFIX }}" --output text --region ${{ inputs.AWS_REGION }})
+          aws ec2 describe-instances --instance-ids $INSTANCE_IDS --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Instance`]]' --output yaml --region ${{ inputs.AWS_REGION }}
+  
+      - name: Start EC2 ${{ inputs.CDK_PREFIX }} Instances
+        run: |
+
+          aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters "Name=tag-key,Values=Instance" "Name=tag-value,Values=${{ inputs.CDK_PREFIX }}" "Name=instance-state-name,Values=stopped" --output text --region ${{ inputs.AWS_REGION }} > instances.txt
+
+          if [ ! -s instances.txt ]; then
+            echo "No STOPPED instances found, nothing to do!"
+            exit 0
+          fi
+
+          INSTANCES=($(cat instances.txt))
+          echo "Start ${#INSTANCES[@]} instances"
+          for INSTANCE in "${INSTANCES[@]}"
+          do 
+            aws ec2 start-instances --instance-ids $INSTANCE  --region ${{ inputs.AWS_REGION }}
+          done
+
+          aws ec2 describe-instances --instance-ids $INSTANCE_IDS --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Instance`]]' --output yaml --region ${{ inputs.AWS_REGION }}
+
   airflow_partial_deploy:
 
     runs-on: ${{ inputs.RUNS_ON }}
@@ -121,64 +203,6 @@ jobs:
             }
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-
-      # start REDSHIFT and INSTANCES
-
-      - name: List Redshift clusters
-        run: |
-          aws redshift describe-clusters --query 'Clusters[*].[ClusterIdentifier,ClusterStatus]' --output text --region ${{ inputs.AWS_REGION }}
-
-      - name: Resume Redshift ${{ inputs.CDK_PREFIX }} cluster
-        run: |
-          CLUSTER_ID=$(aws redshift describe-clusters --tag-keys Instance --tag-values ${{ inputs.CDK_PREFIX }} --tag-keys Stack --tag-values ${{ inputs.CDK_PREFIX }}-datainfra-v2-redshift --query 'Clusters[*].ClusterIdentifier' --output text --region ${{ inputs.AWS_REGION }})
-          echo "Redshift cluster id" $CLUSTER_ID
-
-          STATUS=`aws redshift describe-clusters --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}`
-          if [[ $STATUS == "available" ]]
-          then
-            echo "Cluster" $CLUSTER_ID "is already available, no action."
-          elif [[ $STATUS == "pausing" ]]
-          then
-            echo "Cluster" $CLUSTER_ID "is pausing, failing!"
-            exit 1
-          elif [[ $STATUS == "resuming" ]]
-          then
-            echo "Cluster" $CLUSTER_ID "is resuming, no action!"
-          else
-            echo "Resuming Redshift Cluster" $CLUSTER_ID "status" $STATUS
-            aws redshift resume-cluster --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}
-          fi
-        
-          # do we add a wait for it to resume here or just fire and forget?
-
-          STATUS=`aws redshift describe-clusters --cluster-identifier $CLUSTER_ID --query 'Clusters[*].[ClusterStatus]' --output text  --region ${{ inputs.AWS_REGION }}`
-          echo "STATUS:" $STATUS
-
-      - name: List EC2 ${{ inputs.CDK_PREFIX }} Instances
-        run: |
-          INSTANCE_IDS=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters "Name=tag-key,Values=Instance" "Name=tag-value,Values=${{ inputs.CDK_PREFIX }}" --output text --region ${{ inputs.AWS_REGION }})
-          aws ec2 describe-instances --instance-ids $INSTANCE_IDS --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Instance`]]' --output yaml --region ${{ inputs.AWS_REGION }}
-  
-      - name: Start EC2 ${{ inputs.CDK_PREFIX }} Instances
-        run: |
-
-          aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId]' --filters "Name=tag-key,Values=Instance" "Name=tag-value,Values=${{ inputs.CDK_PREFIX }}" "Name=instance-state-name,Values=stopped" --output text --region ${{ inputs.AWS_REGION }} > instances.txt
-
-          if [ ! -s instances.txt ]; then
-            echo "No STOPPED instances found, nothing to do!"
-            exit 0
-          fi
-
-          INSTANCES=($(cat instances.txt))
-          echo "Start ${#INSTANCES[@]} instances"
-          for INSTANCE in "${INSTANCES[@]}"
-          do 
-            aws ec2 start-instances --instance-ids $INSTANCE  --region ${{ inputs.AWS_REGION }}
-          done
-
-          aws ec2 describe-instances --instance-ids $INSTANCE_IDS --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Instance`]]' --output yaml --region ${{ inputs.AWS_REGION }}
-
-      # end REDSHIFT and INSTANCES
 
       - name: Get changed DAG files including models (if any)
         uses: tj-actions/changed-files@v41
